### ISSUE TITLE
Speech dispatcher doesn't work after after installing.

### ISSUE THREAD

**Issue by yummmy-yummmy** [Elleo/pied#1]
After installing and changing the config, speech dispatcher no longer works for me.
When i run `spd-say "This is a test"`, it doesn't give me an audio output.

Can I revert the changes somehow?

**System Information**
OS: Fedora 39 
Package format: Flatpak

**Comment by yummmy-yummmy** [comment]
Thanks, deleting the config file worked. I don't tinker with these stuff usually so this was my first time using it.

As for `speech-dispatcher`, its `version 0.11.5` and the audio system is `PipeWire`.

**Comment by Elleo** [comment]
Great, glad that's got things working for you again.

Thanks for the extra info, I'll try setting up a Fedora VM and see if I can reproduce the issue there.

**Comment by another-sapiens** [comment]
The following workaround is working for me on Fedora 39: 
Go to `~/.config/speech-dispatcher/modules` and change the part that says...

`$PLAY_COMMAND --raw --channels 1 --rate 16000`

to 

`aplay -r 16000 -c 1 -f S16_LE -t raw`

**Comment by Elleo** [comment]
I've just released version 0.2 which includes a fallback to aplay if paplay isn't available on the host system, thanks for finding this issue!
