### ISSUE TITLE
TTS Simply doesn't work

### ISSUE THREAD

**Issue by fbarbe00** [Elleo/pied#14]
Hi,
I am on Ubuntu 23.10 and have installed the latest version of pied through Snapcraft.

I have used pied to install some UK and US voices, and activated one of them. I have tried using them with the Screen Reader and my web browser's (Firefox) TTS, but this did not produce any sound.

Things I've checked:
- Volume is on, and works properly on music and videos
- Rebooted my computer
- changed the language of my laptop to match voice
- Screen reader voice previously worked

Did I miss anything? Did this happen to anyone else?

**Comment by juanMarinero** [comment]
README says

> for use with [Speech Dispatcher](https://freebsoft.org/speechd)

Thus, install it `sudo apt install espeak-ng`

Open Piped and install "Amy" voice 
Run `spd-say "A rainbow is a metherological phenomenon"`

If not Amy's voice run `sudo systemctl restart speech-dispatcher`

If `spd-say` voice is ok then try [Read-aloud](https://addons.mozilla.org/en-US/firefox/addon/read-aloud/) (or give info about your Screen Reader) set voice as "Auto select" in settings of the add-on (firefox extension).
