### ISSUE TITLE
Pied breaks flatpak update

### ISSUE THREAD

**Issue by benmordecai** [Elleo/pied#18]
`Aborted due to failure (Can't remove org.freedesktop.Platform/x86_64/22.08, it is needed for: com.mikeasoft.pied)`

I am assuming that pied needs a version bump to allow the freedesktop platform to update.

**Comment by Elleo** [comment]
Hi @benmordecai 

I've rebuilt with 24.08 here: https://github.com/Elleo/pied/releases/download/v0.2.1/com.mikeasoft.pied.flatpak

Could you please give the updated package  a quick test to see if it fixes your issue?

Thanks,
Mike

**Comment by benmordecai** [comment]
I tried to install from this flatpak and it appeared to be already uninstalled. I updated the freedesktop platform, and now pied will not install from the flatpak.

**Comment by Elleo** [comment]
Could you post the error you're receiving when attempting to install the new package?

Thanks,
Mike

**Comment by benmordecai** [comment]
It gets stuck on installing and never installs

**Comment by benmordecai** [comment]
Nevermind, that was an error on my end. Apparently there was a hidden authentication request that wasn't being seen by the window manager. I terminated it and tried again and that time I was able to authenticate, then it installed Pied properly and launched fine.

**Comment by Elleo** [comment]
Great, thanks for testing!
