### ISSUE TITLE
spd-say -L returns Failed to get voice list

### ISSUE THREAD

**Issue by themreza** [Elleo/pied#3]
I'm on Ubuntu 20.04, and I have Speech Dispatcher 0.9.1 installed.

After installing Pied and downloading a voice, I could confirm that `spd-say "test"` worked fine, but `spd-say -L` returned the `Failed to get voice list.` error.  For this particular version of Speech Dispatcher, an empty voice list prevents Firefox's Reader View mode from functioning normally. https://support.mozilla.org/en-US/kb/speechd-setup

I noticed that `spd-say -o piper -L` didn't have this issue, so it hinted that the Piper module was probably not being selected as the default output. I then tried adding `DefaultModule piper` to `~/.config/speech-dispatcher/speechd.conf`, and it fixed the issue:

```
$ killall speech-dispatcher
$ spd-say -L
                     NAME                 LANGUAGE                  VARIANT
                    Piper                    en-us                    MALE1
```

This issue is most likely specific to older versions of Speech Dispatcher, before [this fix](https://github.com/brailcom/speechd/commit/43a967b1) was released. An alternative solution is to find a backported binary or to build the binary manually, but for me, this was the quickest fix, so I thought I should share it here in case someone else faces the same issue.

**Comment by Elleo** [comment]
Hi @themreza,

That's great, thanks for figuring that out! I'll include it in the configuration template for the next release
